/*
 * Copyright (C) 2006 Apple Computer, Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */

cpp_quote("/*")
cpp_quote(" * Copyright (C) 2006 Apple Computer, Inc.  All rights reserved.")
cpp_quote(" *")
cpp_quote(" * Redistribution and use in source and binary forms, with or without")
cpp_quote(" * modification, are permitted provided that the following conditions")
cpp_quote(" * are met:")
cpp_quote(" * 1. Redistributions of source code must retain the above copyright")
cpp_quote(" *    notice, this list of conditions and the following disclaimer.")
cpp_quote(" * 2. Redistributions in binary form must reproduce the above copyright")
cpp_quote(" *    notice, this list of conditions and the following disclaimer in the")
cpp_quote(" *    documentation and/or other materials provided with the distribution.")
cpp_quote(" *")
cpp_quote(" * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY")
cpp_quote(" * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE")
cpp_quote(" * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR")
cpp_quote(" * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR")
cpp_quote(" * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,")
cpp_quote(" * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,")
cpp_quote(" * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR")
cpp_quote(" * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY")
cpp_quote(" * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT")
cpp_quote(" * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE")
cpp_quote(" * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. ")
cpp_quote(" */")

import "oaidl.idl";
import "ocidl.idl";

import "IWebView.idl";
import "IWebViewPrivate.idl";
import "IWebUIDelegate.idl";
import "IWebResourceLoadDelegate.idl";
import "IWebDownload.idl";
import "IWebFrameLoadDelegate.idl";
import "IWebPolicyDelegate.idl";
import "IWebFrame.idl";
import "IWebBackForwardList.idl";
import "IWebHistoryItem.idl";
import "IWebScriptObject.idl";
import "IWebPreferences.idl";
import "IWebDocument.idl";
import "IWebURLRequest.idl";
import "IWebDataSource.idl";
import "IWebURLResponse.idl";
import "IWebURLAuthenticationChallenge.idl";
import "IWebError.idl";
import "IWebMutableURLRequest.idl";
import "IWebArchive.idl";
import "IWebResource.idl";
import "IWebFrameView.idl";
import "DOMHTML.idl";
import "IWebIconDatabase.idl";
import "IWebNotificationCenter.idl";
import "IWebNotificationObserver.idl";
import "IWebHistory.idl";
import "IWebCache.idl";

[
#if __ARCHIVE_BUILD__
    uuid(76E5F7F0-18FD-48a2-B549-1159435B513B)
#elif __BUILDBOT__
    uuid(2a748656-625d-4207-b29f-40c95bfeb3a9)
#else
    uuid(D3217C21-2D11-450d-9389-06F0BD4D8AD9)
#endif
]
library WebKit
{
#if __ARCHIVE_BUILD__
    [uuid(4FF47097-3FEA-4b47-AC0E-90725C546490)]
#elif __BUILDBOT__
    [uuid(d6bca079-f61c-4e1e-b453-32a0477d02e3)]
#else
    [uuid(ED2B13E0-66AB-4cc2-9B9F-5B8F85D9AD1D)]
#endif
    coclass WebView {
        interface IWebView;
        interface IWebIBActions;
        interface IWebViewCSS;
        interface IWebViewEditing;
        interface IWebViewUndoableEditing;
        interface IWebViewEditingActions;
        interface IWebNotificationObserver;
        interface IWebViewPrivate;
    }

#if __ARCHIVE_BUILD__
    [uuid(BE8EE509-9894-44ba-9E2F-E29780BCB25C)]
#elif __BUILDBOT__
    [uuid(66827ec1-3aef-4241-bac5-f776b44f030f)]
#else
    [uuid(982FE6C0-60BB-4c12-A3D4-0381428CCCB1)]
#endif
    coclass WebIconDatabase {
        interface IWebIconDatabase;
    }

#if __ARCHIVE_BUILD__
    [uuid(97F3EB52-9EAC-4062-82E1-E5C1E7789DEE)]
#elif __BUILDBOT__
    [uuid(a062ecc3-bb1b-4694-a569-f59e0ad6be0c)]
#else
    [uuid(C77FFC11-EE19-4337-92F6-52BF16B0C1A7)]
#endif
    coclass WebMutableURLRequest {
        interface IWebMutableURLRequest;
    }

#if __ARCHIVE_BUILD__
    [uuid(99B9D99A-060D-4695-8C8F-3AB53156054C)]
#elif __BUILDBOT__
    [uuid(ba590766-0a6f-46c7-b96e-743490d94cb7)]
#else
    [uuid(D2F0B459-88CC-4323-A87C-58057357B2E0)]
#endif
    coclass WebNotificationCenter {
        interface IWebNotificationCenter;
    }

#if __ARCHIVE_BUILD__
    [uuid(4D043991-E844-48b0-8EF7-85FE1AB8829E)]
#elif __BUILDBOT__
    [uuid(a4b9b45d-949f-4c8c-9b92-6fbfcc1caaa2)]
#else
    [uuid(FE0AC8FF-0357-4141-97BE-B663DF80DAB9)]
#endif
    coclass WebHistory {
        interface IWebHistory;
    }

#if __ARCHIVE_BUILD__
    [uuid(97795891-293D-4855-800E-E21987568537)]
#elif __BUILDBOT__
    [uuid(dd653964-4d37-4fb2-9cb6-6a9a97719332)]
#else
    [uuid(20919C16-3B48-4d52-88CC-8DC516E647DE)]
#endif
    coclass CFDictionaryPropertyBag {
        interface IPropertyBag;
    }

#if __ARCHIVE_BUILD__
    [uuid(82F6400A-3CD0-40a3-8EA1-7A23B26D6153)]
#elif __BUILDBOT__
    [uuid(6be190e9-1725-4e4a-88db-6a9fe242c9e5)]
#else
    [uuid(FB97D506-ED53-40bc-815D-07936D7840F6)]
#endif
    coclass WebHistoryItem {
        interface IWebHistoryItem;
    }

#if __ARCHIVE_BUILD__
    [uuid(CB0111F6-168B-467e-8613-23AB37D0493E)]
#elif __BUILDBOT__
    [uuid(f71071fd-a51b-4b69-9eb6-44374405e80c)]
#else
    [uuid(DDAE0034-5E0F-487c-83C0-07626051C17F)]
#endif
    coclass WebCache {
        interface IWebCache;
    }
}
