#include "config.h"

#if PLATFORM(CAIRO)

#include "jcomapi.c"
#include "jdapimin.c"
#include "jdapistd.c"
#include "jdatadst.c"
#include "jdatasrc.c"
#include "jdcoefct.c"
//#include "jdcolor.c"
#include "jddctmgr.c"
//#include "jdhuff.c"
//#include "jdinput.c"
#include "jdmainct.c"
#include "jdmarker.c"
#include "jdmaster.c"
//#include "jdmerge.c"
#include "jdphuff.c"
#include "jdpostct.c"
#include "jdsample.c"
#include "jerror.c"
#include "jfdctflt.c"
#include "jfdctfst.c"
#include "jfdctint.c"
#include "jidctflt.c"
#include "jidctfst.c"
#include "jidctint.c"
//#include "jmemmgr.c"
#include "jmemnobs.c"
#include "jquant1.c"
#include "jquant2.c"
#include "jutils.c"

#endif // PLATFORM(CAIRO)
