#include "config.h"

#if PLATFORM(CAIRO)

#include "cairo/src/cairo-arc.c"
#include "cairo/src/cairo-array.c"
#include "cairo/src/cairo-cache.c"
#include "cairo/src/cairo-clip.c"
#include "cairo/src/cairo-color.c"
#include "cairo/src/cairo-debug.c"
#include "cairo/src/cairo-fixed.c"
#include "cairo/src/cairo-font-options.c"
#include "cairo/src/cairo-font.c"
#include "cairo/src/cairo-gstate.c"
#include "cairo/src/cairo-hash.c"
#include "cairo/src/cairo-hull.c"
#include "cairo/src/cairo-image-surface.c"
#include "cairo/src/cairo-matrix.c"
#include "cairo/src/cairo-meta-surface.c"
#include "cairo/src/cairo-output-stream.c"
#include "cairo/src/cairo-paginated-surface.c"
#include "cairo/src/cairo-path-bounds.c"
#include "cairo/src/cairo-path-data.c"
#include "cairo/src/cairo-path-fill.c"
#include "cairo/src/cairo-path-stroke.c"
#include "cairo/src/cairo-path.c"
#include "cairo/src/cairo-pattern.c"
#include "cairo/src/cairo-pen.c"
#include "cairo/src/cairo-polygon.c"
#include "cairo/src/cairo-region.c"
#include "cairo/src/cairo-scaled-font.c"
#include "cairo/src/cairo-slope.c"
#include "cairo/src/cairo-spline.c"
#include "cairo/src/cairo-stroke-style.c"
#include "cairo/src/cairo-surface-fallback.c"
#include "cairo/src/cairo-surface.c"
#include "cairo/src/cairo-traps.c"
#include "cairo/src/cairo-unicode.c"
#include "cairo/src/cairo-wideint.c"
#include "cairo/src/cairo-win32-font.c"
#include "cairo/src/cairo-win32-surface.c"
#include "cairo/src/cairo.c"

#endif // PLATFORM(CAIRO)
